# ---------------------------
# Jenkins Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          # Jenkins listens on two main ports:
          #  - 8080 for the Web UI
          #  - 50000 for agent connections
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          # Persist Jenkins data (config, job history, etc.)
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          env:
            - name: JAVA_OPTS
              value: "-Xmx1024m" # Example of customizing Java heap size
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc

---
# ---------------------------
# Jenkins Service
# ---------------------------
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
    - name: jnlp
      protocol: TCP
      port: 50000
      nodePort: 30081

---
# ---------------------------
# Jenkins PersistentVolumeClaim (PVC)
# ---------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
